// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qphdhrbmfzunqtiudgcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaGRocmJtZnp1bnF0aXVkZ2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzEyODEsImV4cCI6MjA2OTQ0NzI4MX0.EplB3i_LnNJw5f1GIYX-XLAd3rm7Xx7r60_SrmuzdXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});